server:
  port: 8080

dubbo:
  application:
    name: login-server
  registry:
    address: zookeeper://192.168.31.204:2181

# 配置swagger
swagger:
  basePackage: com.cherry.consumer.controller
  title: CherryAPI
  description: 学习使我们收获满满.
  version: V1.0

spring:
    datasource:
      url: jdbc:mysql://localhost:3306/cherry?useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver