server:
  port: 18080

#配置redis
spring:
  redis:
    host: 127.0.0.1
    port: 6379
#   password: aezxb3JXaE*kqbxR
  freemarker:
    #    设置ftl文件路径
    templateLoaderPath: classpath:/templates/
    #    关闭缓存,及时刷新,上线生产环境需要修改为true
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    allow-request-override: false
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: false
    request-context-attribute: request
    suffix: .html

dubbo:
  application:
    name: tissue-server
  registry:
    address: zookeeper://127.0.0.1:2181
#配置短信平台信息
cherry:
  jwt:
    #盐
    key: cherry
    #超时时间
    ttl: 3600

# 配置swagger
swagger:
  basePackage: com.cherry.consumer.controller
  title: CherryAPI
  description: 学习使我们收获满满.
  version: V1.0
