server:
  port: 18081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #TODO 数据库名字
    url: jdbc:mysql://127.0.0.1:3306/cherry?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
dubbo:
  application:
    name: cherry-dubbo-service
  protocol:
    name: dubbo
    port: 9089
  registry:
    address: zookeeper://192.168.31.204:2181
  scan:
    base-packages: com.cherry.dubbo.impl
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      table-prefix: tb_   # 表名前缀
#      id-type: auto   # id策略为自增长

