server:
  port: 8080

spring:
  application:
    name: cherry-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:18081
          predicates:
            - Path=/api/v1/auth/**

        - id: blog-service
          uri: http://localhost:18082
          predicates:
            - Path=/api/v1/blog/**

dubbo:
  application:
    name: cherry-gateway
  registry:
    address: zookeeper://192.168.31.204:2181
  protocol:
    name: dubbo
    port: -1
